# Generated by Django 4.2.7 on 2023-12-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrooms',
            options={'managed': False, 'verbose_name': 'Аудитории', 'verbose_name_plural': 'Аудитории'},
        ),
    ]
