# Generated by Django 4.2.7 on 2023-12-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0002_remove_user_user_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
