# Generated by Django 4.2.7 on 2023-12-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authorization', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
